### ISSUE TITLE
Captcha Crashes Scraper

### ISSUE THREAD

**Issue by qadfly** [rksm/patreon-scraper#9]
It seems that Patreon's Captcha crashes the scraping process. It happens both '--with-comments' and without. This is the error, I am getting:

`Error fetching posts: TypeError: Cannot read property 'data' of undefined
    at GetPatreonPosts.loadAllPosts (/home/user/patreon-scraper/src/patreon-posts.ts:55:16)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async run (/home/user/patreon-scraper/src/fetch_data.ts:41:16)
`

Everything works fine until the Captcha screen appears and then the error happens.

Would it be possible to implement either:
a) Detect when Captcha screen pops-up, pause the scraping process; let the user solve the captcha and then let the scraping continue 

or

b) Have the scrape 'save', so rather than start from scratch after each error each subsequent scrape would continue from where the previous left off

**Comment by rksm** [comment]
Yeah, that should be possible. I'll need to get into the captcha state. How much do I need to hammer their site to get that to happen?

**Comment by qadfly** [comment]
Shouldn't be too difficult, it will trigger in 60 - 70 posts. Good news is if you trigger it once, it will always crash at captcha until relogin with new cookies
